version: '3.8'

services:
  api:
    build:
     context: .
     dockerfile: Dockerfile
    #image: cgv2
    ports:
      - "3000:3000"
    #volumes:
     # - .:/app
    environment:
      - NODE_ENV=development