version: '3.8'

services:
  api:
    build:
     context: .
     dockerfile: Dockerfile
    restart: "always"
    #image: cgv2
    ports:
      - "3000:3000"
    volumes:
      - ./certificates:/app/certificates
    environment:
      - NODE_ENV=development
